"""
Stress Test - Module B
=======================
Runs a large number of requests (hundreds/thousands) under load.
Measures response time, correctness, and system behavior.

Requires: Next.js dev server running on http://localhost:3000

Run:  python3 stress/stress_test.py
"""

import requests
import threading
import time
import statistics
import sys
import os

BASE_URL = os.environ.get("API_BASE_URL", "http://localhost:3000/api")
TOTAL_REQUESTS = 0
SUCCESSFUL_REQUESTS = 0
FAILED_REQUESTS = 0
RESPONSE_TIMES = []
LOCK = threading.Lock()


def record_request(success, response_time):
    global TOTAL_REQUESTS, SUCCESSFUL_REQUESTS, FAILED_REQUESTS
    with LOCK:
        TOTAL_REQUESTS += 1
        if success:
            SUCCESSFUL_REQUESTS += 1
        else:
            FAILED_REQUESTS += 1
        RESPONSE_TIMES.append(response_time)


def login_as_admin():
    """Login as admin and return the JWT token."""
    resp = requests.post(
        f"{BASE_URL}/auth/login",
        json={
            "username": "admin",
            "password": "admin123",
        },
        timeout=10,
    )
    if resp.status_code == 200:
        return resp.json().get("token")
    return None


def worker_read_requests(token, num_requests, worker_id):
    """Worker that sends read requests."""
    headers = {"Authorization": f"Bearer {token}"}
    endpoints = [
        f"{BASE_URL}/rooms",
        f"{BASE_URL}/students",
        f"{BASE_URL}/allocations",
        f"{BASE_URL}/gatepasses",
        f"{BASE_URL}/maintenance",
    ]

    for i in range(num_requests):
        endpoint = endpoints[i % len(endpoints)]
        start = time.time()
        try:
            resp = requests.get(endpoint, headers=headers, timeout=10)
            elapsed = time.time() - start
            record_request(resp.status_code == 200, elapsed)
        except Exception:
            elapsed = time.time() - start
            record_request(False, elapsed)


def worker_mixed_requests(token, num_requests, worker_id):
    """Worker that sends a mix of read and write requests."""
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

    for i in range(num_requests):
        op = i % 5

        start = time.time()
        try:
            if op == 0:
                # Read rooms
                resp = requests.get(f"{BASE_URL}/rooms", headers=headers, timeout=10)
            elif op == 1:
                # Read students
                resp = requests.get(f"{BASE_URL}/students", headers=headers, timeout=10)
            elif op == 2:
                # Read allocations
                resp = requests.get(
                    f"{BASE_URL}/allocations", headers=headers, timeout=10
                )
            elif op == 3:
                # Read gatepasses
                resp = requests.get(
                    f"{BASE_URL}/gatepasses", headers=headers, timeout=10
                )
            else:
                # Write: create a maintenance request (safe write that doesn't affect critical data)
                resp = requests.post(
                    f"{BASE_URL}/maintenance",
                    headers=headers,
                    json={
                        "reportedBy": 3,
                        "title": f"Stress test item {worker_id}-{i}",
                        "description": "Auto-generated by stress test",
                        "priority": "Low",
                        "status": "Open",
                    },
                    timeout=10,
                )

            elapsed = time.time() - start
            record_request(resp.status_code in (200, 201), elapsed)
        except Exception:
            elapsed = time.time() - start
            record_request(False, elapsed)


def run_stress_test(num_workers=10, requests_per_worker=100):
    """
    Run stress test with specified number of workers and requests.

    Args:
        num_workers: Number of concurrent threads.
        requests_per_worker: Number of requests per thread.
    """
    total_target = num_workers * requests_per_worker

    print("=" * 70)
    print(f"MODULE B: Stress Test ({total_target} requests, {num_workers} workers)")
    print("=" * 70)

    token = login_as_admin()
    if not token:
        print("[ERROR] Cannot authenticate. Is the dev server running?")
        print("  Run: cd module-b && bun run dev")
        return False

    print(
        f"\nLaunching {num_workers} workers x {requests_per_worker} requests = {total_target} total..."
    )

    # Reset counters
    global TOTAL_REQUESTS, SUCCESSFUL_REQUESTS, FAILED_REQUESTS, RESPONSE_TIMES
    TOTAL_REQUESTS = 0
    SUCCESSFUL_REQUESTS = 0
    FAILED_REQUESTS = 0
    RESPONSE_TIMES = []

    threads = []
    start = time.time()

    for i in range(num_workers):
        if i % 2 == 0:
            t = threading.Thread(
                target=worker_read_requests, args=(token, requests_per_worker, i)
            )
        else:
            t = threading.Thread(
                target=worker_mixed_requests, args=(token, requests_per_worker, i)
            )
        threads.append(t)

    # Start all threads
    for t in threads:
        t.start()

    # Wait for completion
    for t in threads:
        t.join(timeout=120)

    elapsed = time.time() - start

    # Calculate statistics
    if RESPONSE_TIMES:
        avg_time = statistics.mean(RESPONSE_TIMES)
        median_time = statistics.median(RESPONSE_TIMES)
        p95_time = sorted(RESPONSE_TIMES)[int(len(RESPONSE_TIMES) * 0.95)]
        p99_time = sorted(RESPONSE_TIMES)[int(len(RESPONSE_TIMES) * 0.99)]
        min_time = min(RESPONSE_TIMES)
        max_time = max(RESPONSE_TIMES)
    else:
        avg_time = median_time = p95_time = p99_time = min_time = max_time = 0

    throughput = SUCCESSFUL_REQUESTS / elapsed if elapsed > 0 else 0

    # Report
    print(f"\n{'=' * 70}")
    print("STRESS TEST RESULTS")
    print(f"{'=' * 70}")
    print(f"  Total requests:     {TOTAL_REQUESTS}")
    print(f"  Successful:         {SUCCESSFUL_REQUESTS}")
    print(f"  Failed:             {FAILED_REQUESTS}")
    print(
        f"  Success rate:       {SUCCESSFUL_REQUESTS / TOTAL_REQUESTS * 100:.1f}%"
        if TOTAL_REQUESTS > 0
        else "  Success rate: N/A"
    )
    print(f"  Total time:         {elapsed:.2f}s")
    print(f"  Throughput:         {throughput:.1f} req/s")
    print(f"\n  Response Times:")
    print(f"    Min:              {min_time * 1000:.1f}ms")
    print(f"    Avg:              {avg_time * 1000:.1f}ms")
    print(f"    Median:           {median_time * 1000:.1f}ms")
    print(f"    P95:              {p95_time * 1000:.1f}ms")
    print(f"    P99:              {p99_time * 1000:.1f}ms")
    print(f"    Max:              {max_time * 1000:.1f}ms")

    # Verify data integrity
    print(f"\n  Data Integrity Check:")
    headers = {"Authorization": f"Bearer {token}"}
    try:
        resp = requests.get(f"{BASE_URL}/rooms", headers=headers, timeout=10)
        if resp.status_code == 200:
            rooms = resp.json()
            print(f"    Rooms: {len(rooms)} records (API responsive)")
            # Check for corruption: all rooms should have valid fields
            corrupt = 0
            for room in rooms:
                room_data = room.get("room", room)  # handle both flat and joined response
                if not all(
                    k in room_data for k in ["roomId", "blockId", "roomNumber", "capacity"]
                ):
                    corrupt += 1
            if corrupt > 0:
                print(f"    [WARN] {corrupt} rooms have missing fields")
            else:
                print(f"    [OK] All room records have valid fields")
    except Exception as e:
        print(f"    [ERROR] Could not verify data integrity: {e}")

    success = FAILED_REQUESTS == 0
    print(
        f"\n  {'[PASS]' if success else '[FAIL]'} Stress test: {SUCCESSFUL_REQUESTS}/{TOTAL_REQUESTS} requests succeeded"
    )

    return success


def main():
    # Run a 500-request stress test (50 workers x 10 requests each)
    # Adjust based on your system capacity
    num_workers = int(os.environ.get("STRESS_WORKERS", "50"))
    requests_per_worker = int(os.environ.get("STRESS_REQUESTS", "10"))

    success = run_stress_test(
        num_workers=num_workers, requests_per_worker=requests_per_worker
    )
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
